### ISSUE TITLE
Getting media clips throws exception

### ISSUE THREAD

**Issue by chinshr** [synctv/synctv-ruby-client#2]
In order to get media clips we need to call `.../api/v2/media/1/clips.json`, which maps to `Media.find(1).get(:clips)`, but it throws a multi json exception. It also appears to perform two GET calls instead of just one.

```
[GET] https://tf1-staging.synctv.com:443/api/v2/media/1.json?access_id=389305&signature=d81acb4ece7e9b8b586d864e308f28bc
 [GET] https://tf1-staging.synctv.com:443/api/v2/media/1/clips.json?access_id=389305&signature=d81acb4ece7e9b8b586d864e308f28bc
ActiveResource::ResourceNotFound: /Users/juergen/.rvm/gems/ruby-1.9.3-p392@drivethru/gems/multi_json-1.7.6/lib/multi_json/adapters/oj.rb:15:in `load': unexpected character at line 1, column 1 [parse.c:626] (MultiJson::LoadError)
    from /Users/juergen/.rvm/gems/ruby-1.9.3-p392@drivethru/gems/multi_json-1.7.6/lib/multi_json/adapters/oj.rb:15:in `load'
    from /Users/juergen/.rvm/gems/ruby-1.9.3-p392@drivethru/gems/multi_json-1.7.6/lib/multi_json/adapter.rb:25:in `load'
    from /Users/juergen/.rvm/gems/ruby-1.9.3-p392@drivethru/gems/multi_json-1.7.6/lib/multi_json.rb:132:in `load'
    from /Users/juergen/.rvm/gems/ruby-1.9.3-p392@drivethru/gems/activesupport-3.2.13/lib/active_support/json/decoding.rb:15:in `decode'
    from /Users/juergen/.rvm/gems/ruby-1.9.3-p392@drivethru/bundler/gems/synctv-ruby-client-ee49597409e1/lib/synctv/active_resource/extension.rb:38:in `to_s_with_envelope'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb.rb:168:in `write'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb.rb:168:in `print'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb.rb:168:in `block (2 levels) in eval_input'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb.rb:273:in `signal_status'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb.rb:156:in `block in eval_input'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb/ruby-lex.rb:243:in `block (2 levels) in each_top_level_statement'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `loop'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `block in each_top_level_statement'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `catch'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `each_top_level_statement'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb.rb:155:in `eval_input'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb.rb:70:in `block in start'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb.rb:69:in `catch'
    from /Users/juergen/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/irb.rb:69:in `start'
    from /Users/juergen/.rvm/gems/ruby-1.9.3-p392@drivethru/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
    from /Users/juergen/.rvm/gems/ruby-1.9.3-p392@drivethru/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
    from /Users/juergen/.rvm/gems/ruby-1.9.3-p392@drivethru/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by chinshr** [comment]
The call to `Media.get(:clips)` is wrong, it should be `Media.get("media/clips")` instead. 
- Added better exception handling on `500` errors. 
- The Media resource has a `clips` instance method now, returning a collection of media clips. So the simplified call is `Media.find(1).clips`.
